-- Poker Ledger schema
-- Run this in the Supabase SQL editor (Dashboard > SQL Editor > New query).
-- Safe to re-run: it only creates objects if they don't already exist.

create extension if not exists "pgcrypto";

-- A "series" is a recurring game group. The invite_token is the secret that
-- grants access to the series via its URL. It is generated by the app.
create table if not exists series (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  currency     text not null default 'kr',
  invite_token text not null unique,
  created_at   timestamptz not null default now()
);

-- Players belong to a series. A player who "joins for a day" still lives here;
-- they simply only have results for the games they actually played.
create table if not exists players (
  id         uuid primary key default gen_random_uuid(),
  series_id  uuid not null references series(id) on delete cascade,
  name       text not null,
  created_at timestamptz not null default now()
);

create index if not exists players_series_idx on players(series_id);

-- One row per night of poker.
create table if not exists games (
  id         uuid primary key default gen_random_uuid(),
  series_id  uuid not null references series(id) on delete cascade,
  played_on  date not null default current_date,
  note       text,
  created_at timestamptz not null default now()
);

create index if not exists games_series_idx on games(series_id);

-- One row per player per game. net = cash_out - buy_in (computed in app).
create table if not exists game_results (
  id        uuid primary key default gen_random_uuid(),
  game_id   uuid not null references games(id) on delete cascade,
  player_id uuid not null references players(id) on delete cascade,
  buy_in    numeric(10,2) not null default 0,
  cash_out  numeric(10,2) not null default 0,
  unique (game_id, player_id)
);

create index if not exists game_results_game_idx on game_results(game_id);
create index if not exists game_results_player_idx on game_results(player_id);

-- Lock the tables down to anyone using the public (anon) API key.
-- The app talks to the database only from the server using the service-role
-- key, which bypasses row-level security. With RLS enabled and no policies,
-- the anon key can read/write nothing -- so a leaked anon key is harmless.
alter table series        enable row level security;
alter table players       enable row level security;
alter table games         enable row level security;
alter table game_results  enable row level security;
